# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\EGOR\Desktop\cursach\Course\AdminWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 309)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 751, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.refresh_tbl = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_tbl.setGeometry(QtCore.QRect(20, 210, 161, 41))
        self.refresh_tbl.setObjectName("refresh_tbl")
        self.insert_btn = QtWidgets.QPushButton(self.centralwidget)
        self.insert_btn.setGeometry(QtCore.QRect(600, 210, 161, 41))
        self.insert_btn.setObjectName("insert_btn")
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_btn.setGeometry(QtCore.QRect(200, 210, 161, 41))
        self.delete_btn.setObjectName("delete_btn")
        self.update_btn = QtWidgets.QPushButton(self.centralwidget)
        self.update_btn.setGeometry(QtCore.QRect(370, 210, 221, 41))
        self.update_btn.setObjectName("update_btn")
        self.lgn_box = QtWidgets.QComboBox(self.centralwidget)
        self.lgn_box.setGeometry(QtCore.QRect(200, 260, 161, 31))
        self.lgn_box.setObjectName("lgn_box")
        self.pwd_line = QtWidgets.QLineEdit(self.centralwidget)
        self.pwd_line.setGeometry(QtCore.QRect(370, 260, 221, 31))
        self.pwd_line.setObjectName("pwd_line")
        self.lgn_line = QtWidgets.QLineEdit(self.centralwidget)
        self.lgn_line.setGeometry(QtCore.QRect(600, 260, 161, 31))
        self.lgn_line.setObjectName("lgn_line")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Окно суперпользователя"))
        self.refresh_tbl.setText(_translate("MainWindow", "Обновить"))
        self.insert_btn.setText(_translate("MainWindow", "Добавить пользователя"))
        self.delete_btn.setText(_translate("MainWindow", "Удалить пользователя"))
        self.update_btn.setText(_translate("MainWindow", "Изменить пароль пользователя"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
