# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\EGOR\Desktop\cursach\Course\ClientRegistrationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistrationWindow(object):
    def setupUi(self, RegistrationWindow):
        RegistrationWindow.setObjectName("RegistrationWindow")
        RegistrationWindow.resize(361, 554)
        self.lgn_lbl = QtWidgets.QLabel(RegistrationWindow)
        self.lgn_lbl.setGeometry(QtCore.QRect(30, 20, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lgn_lbl.setFont(font)
        self.lgn_lbl.setObjectName("lgn_lbl")
        self.lgn_line = QtWidgets.QLineEdit(RegistrationWindow)
        self.lgn_line.setGeometry(QtCore.QRect(30, 50, 301, 31))
        self.lgn_line.setObjectName("lgn_line")
        self.pwd_lbl = QtWidgets.QLabel(RegistrationWindow)
        self.pwd_lbl.setGeometry(QtCore.QRect(30, 90, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pwd_lbl.setFont(font)
        self.pwd_lbl.setObjectName("pwd_lbl")
        self.pwd_line = QtWidgets.QLineEdit(RegistrationWindow)
        self.pwd_line.setGeometry(QtCore.QRect(30, 120, 301, 31))
        self.pwd_line.setObjectName("pwd_line")
        self.phone_lbl = QtWidgets.QLabel(RegistrationWindow)
        self.phone_lbl.setGeometry(QtCore.QRect(30, 160, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phone_lbl.setFont(font)
        self.phone_lbl.setObjectName("phone_lbl")
        self.phone_line = QtWidgets.QLineEdit(RegistrationWindow)
        self.phone_line.setGeometry(QtCore.QRect(30, 190, 301, 31))
        self.phone_line.setObjectName("phone_line")
        self.name_lbl = QtWidgets.QLabel(RegistrationWindow)
        self.name_lbl.setGeometry(QtCore.QRect(30, 230, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_lbl.setFont(font)
        self.name_lbl.setObjectName("name_lbl")
        self.name_line = QtWidgets.QLineEdit(RegistrationWindow)
        self.name_line.setGeometry(QtCore.QRect(30, 260, 301, 31))
        self.name_line.setObjectName("name_line")
        self.passport_lbl = QtWidgets.QLabel(RegistrationWindow)
        self.passport_lbl.setGeometry(QtCore.QRect(30, 300, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.passport_lbl.setFont(font)
        self.passport_lbl.setObjectName("passport_lbl")
        self.passport_line = QtWidgets.QLineEdit(RegistrationWindow)
        self.passport_line.setGeometry(QtCore.QRect(30, 330, 301, 31))
        self.passport_line.setObjectName("passport_line")
        self.drv_line = QtWidgets.QLineEdit(RegistrationWindow)
        self.drv_line.setGeometry(QtCore.QRect(30, 400, 301, 31))
        self.drv_line.setObjectName("drv_line")
        self.drv_lbl = QtWidgets.QLabel(RegistrationWindow)
        self.drv_lbl.setGeometry(QtCore.QRect(30, 370, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.drv_lbl.setFont(font)
        self.drv_lbl.setObjectName("drv_lbl")
        self.reg_btn = QtWidgets.QPushButton(RegistrationWindow)
        self.reg_btn.setGeometry(QtCore.QRect(30, 450, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reg_btn.setFont(font)
        self.reg_btn.setObjectName("reg_btn")
        self.exit_btn = QtWidgets.QPushButton(RegistrationWindow)
        self.exit_btn.setGeometry(QtCore.QRect(30, 500, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exit_btn.setFont(font)
        self.exit_btn.setObjectName("exit_btn")

        self.retranslateUi(RegistrationWindow)
        QtCore.QMetaObject.connectSlotsByName(RegistrationWindow)

    def retranslateUi(self, RegistrationWindow):
        _translate = QtCore.QCoreApplication.translate
        RegistrationWindow.setWindowTitle(_translate("RegistrationWindow", "Регистрация"))
        self.lgn_lbl.setText(_translate("RegistrationWindow", "Логин"))
        self.pwd_lbl.setText(_translate("RegistrationWindow", "Пароль"))
        self.phone_lbl.setText(_translate("RegistrationWindow", "Телефон (только цифры)"))
        self.name_lbl.setText(_translate("RegistrationWindow", "ФИО"))
        self.passport_lbl.setText(_translate("RegistrationWindow", "Паспортные данные (слитно)"))
        self.drv_lbl.setText(_translate("RegistrationWindow", "Номер водительских прав"))
        self.reg_btn.setText(_translate("RegistrationWindow", "Зарегистрироваться"))
        self.exit_btn.setText(_translate("RegistrationWindow", "Закрыть окно"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegistrationWindow = QtWidgets.QDialog()
    ui = Ui_RegistrationWindow()
    ui.setupUi(RegistrationWindow)
    RegistrationWindow.show()
    sys.exit(app.exec_())
