# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\EGOR\Desktop\cursach\Course\ClientOrderWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClientOrderWindow(object):
    def setupUi(self, ClientOrderWindow):
        ClientOrderWindow.setObjectName("ClientOrderWindow")
        ClientOrderWindow.resize(352, 180)
        self.confirm_btn = QtWidgets.QPushButton(ClientOrderWindow)
        self.confirm_btn.setGeometry(QtCore.QRect(90, 130, 171, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.confirm_btn.setFont(font)
        self.confirm_btn.setObjectName("confirm_btn")
        self.car_box = QtWidgets.QComboBox(ClientOrderWindow)
        self.car_box.setGeometry(QtCore.QRect(250, 40, 73, 31))
        self.car_box.setObjectName("car_box")
        self.descr_line = QtWidgets.QLineEdit(ClientOrderWindow)
        self.descr_line.setGeometry(QtCore.QRect(140, 90, 181, 21))
        self.descr_line.setObjectName("descr_line")
        self.car_lbl = QtWidgets.QLabel(ClientOrderWindow)
        self.car_lbl.setGeometry(QtCore.QRect(30, 30, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.car_lbl.setFont(font)
        self.car_lbl.setObjectName("car_lbl")
        self.descr_lbl = QtWidgets.QLabel(ClientOrderWindow)
        self.descr_lbl.setGeometry(QtCore.QRect(30, 90, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.descr_lbl.setFont(font)
        self.descr_lbl.setObjectName("descr_lbl")

        self.retranslateUi(ClientOrderWindow)
        QtCore.QMetaObject.connectSlotsByName(ClientOrderWindow)

    def retranslateUi(self, ClientOrderWindow):
        _translate = QtCore.QCoreApplication.translate
        ClientOrderWindow.setWindowTitle(_translate("ClientOrderWindow", "Окно заказа"))
        self.confirm_btn.setText(_translate("ClientOrderWindow", "Подтвердить заказ"))
        self.car_lbl.setText(_translate("ClientOrderWindow", "Выберите номер машины"))
        self.descr_lbl.setText(_translate("ClientOrderWindow", "Цель аренды"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ClientOrderWindow = QtWidgets.QDialog()
    ui = Ui_ClientOrderWindow()
    ui.setupUi(ClientOrderWindow)
    ClientOrderWindow.show()
    sys.exit(app.exec_())
