# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\EGOR\Desktop\cursach\Course\ClientWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 696)
        MainWindow.setStyleSheet("QWidget{\n"
"\n"
"    background-color: rgb(44, 44, 64);\n"
"}\n"
"QPushButton{\n"
"    \n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(170, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold\n"
"}\n"
"QPushButton#delete_btn{\n"
"    \n"
"    background-color: rgb(209, 0, 0);\n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"    font-weight: bold\n"
"\n"
"}\n"
"QLabel{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    border-top-color: rgba(255, 255, 255, 0);\n"
"    border-right-color: rgba(255, 255, 255, 0);\n"
"    border-left-color: rgba(255, 255, 255, 0);\n"
"    background-color: rgb(50, 50, 64);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLabel#inf_lbl{\n"
"    \n"
"    font-weight: bold\n"
"}\n"
"QComboBox{\n"
"    background-color: rgb(50, 50, 64);\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"}"
"QTableWidget{\n"
"    background-color: rgb(50, 50, 64);\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"}"
)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 791, 192))
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.passport_lbl = QtWidgets.QLabel(self.centralwidget)
        self.passport_lbl.setGeometry(QtCore.QRect(520, 540, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.passport_lbl.setFont(font)
        self.passport_lbl.setObjectName("passport_lbl")
        self.phone_lbl = QtWidgets.QLabel(self.centralwidget)
        self.phone_lbl.setGeometry(QtCore.QRect(520, 460, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phone_lbl.setFont(font)
        self.phone_lbl.setObjectName("phone_lbl")
        self.update_btn = QtWidgets.QPushButton(self.centralwidget)
        self.update_btn.setGeometry(QtCore.QRect(520, 630, 281, 41))
        self.update_btn.setObjectName("update_btn")
        self.phone_line = QtWidgets.QLineEdit(self.centralwidget)
        self.phone_line.setGeometry(QtCore.QRect(520, 490, 281, 31))
        self.phone_line.setObjectName("phone_line")
        self.passport_line = QtWidgets.QLineEdit(self.centralwidget)
        self.passport_line.setGeometry(QtCore.QRect(520, 570, 281, 31))
        self.passport_line.setObjectName("passport_line")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 220, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setFrame(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.trip_info_btn = QtWidgets.QPushButton(self.centralwidget)
        self.trip_info_btn.setGeometry(QtCore.QRect(10, 260, 201, 41))
        self.trip_info_btn.setObjectName("trip_info_btn")
        self.insert_btn = QtWidgets.QPushButton(self.centralwidget)
        self.insert_btn.setGeometry(QtCore.QRect(220, 260, 201, 41))
        self.insert_btn.setObjectName("insert_btn")
        self.name_lbl = QtWidgets.QLabel(self.centralwidget)
        self.name_lbl.setGeometry(QtCore.QRect(520, 380, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_lbl.setFont(font)
        self.name_lbl.setObjectName("name_lbl")
        self.name_line = QtWidgets.QLineEdit(self.centralwidget)
        self.name_line.setGeometry(QtCore.QRect(520, 410, 281, 31))
        self.name_line.setObjectName("name_line")
        self.inf_lbl = QtWidgets.QLabel(self.centralwidget)
        self.inf_lbl.setGeometry(QtCore.QRect(520, 330, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.inf_lbl.setFont(font)
        self.inf_lbl.setObjectName("inf_lbl")
        self.find_btn = QtWidgets.QPushButton(self.centralwidget)
        self.find_btn.setGeometry(QtCore.QRect(10, 380, 411, 41))
        self.find_btn.setObjectName("find_btn")
        self.brand_line = QtWidgets.QLineEdit(self.centralwidget)
        self.brand_line.setGeometry(QtCore.QRect(150, 320, 271, 31))
        self.brand_line.setFrame(True)
        self.brand_line.setObjectName("brand_line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 320, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_btn.setGeometry(QtCore.QRect(10, 440, 411, 41))
        self.delete_btn.setObjectName("delete_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Окно клиента"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Код поездки"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Номер машины"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Дата и время создания заказа"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Описание цели заказа"))
        self.passport_lbl.setText(_translate("MainWindow", "Паспортные данные"))
        self.phone_lbl.setText(_translate("MainWindow", "Телефон"))
        self.update_btn.setText(_translate("MainWindow", "Обновить информацию"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Заказы"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Машины"))
        self.trip_info_btn.setText(_translate("MainWindow", "Информация о поездке"))
        self.insert_btn.setText(_translate("MainWindow", "Новый заказ"))
        self.name_lbl.setText(_translate("MainWindow", "ФИО"))
        self.inf_lbl.setText(_translate("MainWindow", "Информация о пользователе:"))
        self.find_btn.setText(_translate("MainWindow", "Найти машину по бренду"))
        self.label.setText(_translate("MainWindow", "Введите брэнд"))
        self.delete_btn.setText(_translate("MainWindow", "Удалить аккаунт"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
