# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\EGOR\Desktop\cursach\Course\ClientRegistrationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistrationWindow(object):
    def setupUi(self, RegistrationWindow):
        RegistrationWindow.setObjectName("RegistrationWindow")
        RegistrationWindow.resize(503, 752)
        RegistrationWindow.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(170, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold\n"
"}\n"
"QPushButton#exit_btn{\n"
"    \n"
"    background-color: rgb(209, 0, 0);\n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"    font-weight: bold\n"
"\n"
"}\n"
"QDialog{\n"
"\n"
"    background-color: rgb(44, 44, 64);\n"
"}\n"
"QLabel{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    border-top-color: rgba(255, 255, 255, 0);\n"
"    border-right-color: rgba(255, 255, 255, 0);\n"
"    border-left-color: rgba(255, 255, 255, 0);\n"
"    background-color: rgb(50, 50, 64);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.lgn_lbl = QtWidgets.QLabel(RegistrationWindow)
        self.lgn_lbl.setGeometry(QtCore.QRect(90, 110, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lgn_lbl.setFont(font)
        self.lgn_lbl.setObjectName("lgn_lbl")
        self.lgn_line = QtWidgets.QLineEdit(RegistrationWindow)
        self.lgn_line.setGeometry(QtCore.QRect(90, 140, 301, 31))
        self.lgn_line.setObjectName("lgn_line")
        self.pwd_lbl = QtWidgets.QLabel(RegistrationWindow)
        self.pwd_lbl.setGeometry(QtCore.QRect(90, 180, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pwd_lbl.setFont(font)
        self.pwd_lbl.setObjectName("pwd_lbl")
        self.pwd_line = QtWidgets.QLineEdit(RegistrationWindow)
        self.pwd_line.setGeometry(QtCore.QRect(90, 210, 301, 31))
        self.pwd_line.setObjectName("pwd_line")
        self.phone_lbl = QtWidgets.QLabel(RegistrationWindow)
        self.phone_lbl.setGeometry(QtCore.QRect(90, 280, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phone_lbl.setFont(font)
        self.phone_lbl.setObjectName("phone_lbl")
        self.phone_line = QtWidgets.QLineEdit(RegistrationWindow)
        self.phone_line.setGeometry(QtCore.QRect(90, 310, 301, 31))
        self.phone_line.setObjectName("phone_line")
        self.name_lbl = QtWidgets.QLabel(RegistrationWindow)
        self.name_lbl.setGeometry(QtCore.QRect(90, 350, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_lbl.setFont(font)
        self.name_lbl.setObjectName("name_lbl")
        self.name_line = QtWidgets.QLineEdit(RegistrationWindow)
        self.name_line.setGeometry(QtCore.QRect(90, 380, 301, 31))
        self.name_line.setObjectName("name_line")
        self.passport_lbl = QtWidgets.QLabel(RegistrationWindow)
        self.passport_lbl.setGeometry(QtCore.QRect(90, 420, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.passport_lbl.setFont(font)
        self.passport_lbl.setObjectName("passport_lbl")
        self.passport_line = QtWidgets.QLineEdit(RegistrationWindow)
        self.passport_line.setGeometry(QtCore.QRect(90, 450, 301, 31))
        self.passport_line.setObjectName("passport_line")
        self.drv_line = QtWidgets.QLineEdit(RegistrationWindow)
        self.drv_line.setGeometry(QtCore.QRect(90, 520, 301, 31))
        self.drv_line.setObjectName("drv_line")
        self.drv_lbl = QtWidgets.QLabel(RegistrationWindow)
        self.drv_lbl.setGeometry(QtCore.QRect(90, 490, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.drv_lbl.setFont(font)
        self.drv_lbl.setObjectName("drv_lbl")
        self.reg_btn = QtWidgets.QPushButton(RegistrationWindow)
        self.reg_btn.setGeometry(QtCore.QRect(90, 580, 301, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.reg_btn.setFont(font)
        self.reg_btn.setObjectName("reg_btn")
        self.exit_btn = QtWidgets.QPushButton(RegistrationWindow)
        self.exit_btn.setGeometry(QtCore.QRect(90, 640, 301, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.exit_btn.setFont(font)
        self.exit_btn.setObjectName("exit_btn")
        self.main_lbl = QtWidgets.QLabel(RegistrationWindow)
        self.main_lbl.setGeometry(QtCore.QRect(120, 20, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.main_lbl.setFont(font)
        self.main_lbl.setObjectName("main_lbl")

        self.retranslateUi(RegistrationWindow)
        QtCore.QMetaObject.connectSlotsByName(RegistrationWindow)

    def retranslateUi(self, RegistrationWindow):
        _translate = QtCore.QCoreApplication.translate
        RegistrationWindow.setWindowTitle(_translate("RegistrationWindow", "Регистрация"))
        self.lgn_lbl.setText(_translate("RegistrationWindow", "Логин"))
        self.pwd_lbl.setText(_translate("RegistrationWindow", "Придумайте пароль"))
        self.phone_lbl.setText(_translate("RegistrationWindow", "Телефон (только цифры)"))
        self.name_lbl.setText(_translate("RegistrationWindow", "ФИО"))
        self.passport_lbl.setText(_translate("RegistrationWindow", "Паспортные данные (слитно)"))
        self.drv_lbl.setText(_translate("RegistrationWindow", "Номер водительской лицензии"))
        self.reg_btn.setText(_translate("RegistrationWindow", "Зарегистрироваться"))
        self.exit_btn.setText(_translate("RegistrationWindow", "Закрыть окно"))
        self.main_lbl.setText(_translate("RegistrationWindow", "Регистрация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegistrationWindow = QtWidgets.QDialog()
    ui = Ui_RegistrationWindow()
    ui.setupUi(RegistrationWindow)
    RegistrationWindow.show()
    sys.exit(app.exec_())
