# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\EGOR\Desktop\cursach\Course\LoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(401, 359)
        LoginWindow.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(170, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#exit_btn{\n"
"    \n"
"    background-color: rgb(209, 0, 0);\n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"    font-weight: bold\n"
"\n"
"}\n"
"QDialog{\n"
"\n"
"    background-color: rgb(44, 44, 64);\n"
"}\n"
"QLabel{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit{\n"
"    \n"
"    background-color: rgb(50, 50, 64);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.main_lbl = QtWidgets.QLabel(LoginWindow)
        self.main_lbl.setGeometry(QtCore.QRect(150, 0, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.main_lbl.setFont(font)
        self.main_lbl.setObjectName("main_lbl")
        self.lgn_lbl = QtWidgets.QLabel(LoginWindow)
        self.lgn_lbl.setGeometry(QtCore.QRect(30, 80, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lgn_lbl.setFont(font)
        self.lgn_lbl.setObjectName("lgn_lbl")
        self.lgn_line = QtWidgets.QLineEdit(LoginWindow)
        self.lgn_line.setGeometry(QtCore.QRect(30, 110, 341, 31))
        self.lgn_line.setObjectName("lgn_line")
        self.pwd_lbl = QtWidgets.QLabel(LoginWindow)
        self.pwd_lbl.setGeometry(QtCore.QRect(30, 160, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pwd_lbl.setFont(font)
        self.pwd_lbl.setObjectName("pwd_lbl")
        self.pwd_line = QtWidgets.QLineEdit(LoginWindow)
        self.pwd_line.setGeometry(QtCore.QRect(30, 190, 341, 31))
        self.pwd_line.setObjectName("pwd_line")
        self.reg_btn = QtWidgets.QPushButton(LoginWindow)
        self.reg_btn.setGeometry(QtCore.QRect(30, 240, 111, 41))
        self.reg_btn.setObjectName("reg_btn")
        self.lgn_btn = QtWidgets.QPushButton(LoginWindow)
        self.lgn_btn.setGeometry(QtCore.QRect(160, 240, 211, 41))
        self.lgn_btn.setObjectName("lgn_btn")
        self.exit_btn = QtWidgets.QPushButton(LoginWindow)
        self.exit_btn.setGeometry(QtCore.QRect(30, 300, 341, 41))
        self.exit_btn.setObjectName("exit_btn")

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Вход"))
        self.main_lbl.setText(_translate("LoginWindow", "Вход"))
        self.lgn_lbl.setText(_translate("LoginWindow", "Ваш логин"))
        self.pwd_lbl.setText(_translate("LoginWindow", "Ваш пароль"))
        self.reg_btn.setText(_translate("LoginWindow", "Регистрация"))
        self.lgn_btn.setText(_translate("LoginWindow", "Войти"))
        self.exit_btn.setText(_translate("LoginWindow", "Выйти из приложения"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QDialog()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
