# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\EGOR\Desktop\cursach\Course\TechnicalServiceWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(421, 235)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(230, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.car_box = QtWidgets.QComboBox(Dialog)
        self.car_box.setGeometry(QtCore.QRect(150, 10, 41, 31))
        self.car_box.setObjectName("car_box")
        self.workshop_box = QtWidgets.QComboBox(Dialog)
        self.workshop_box.setGeometry(QtCore.QRect(360, 10, 41, 31))
        self.workshop_box.setObjectName("workshop_box")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(230, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 120, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.desc_line = QtWidgets.QLineEdit(Dialog)
        self.desc_line.setGeometry(QtCore.QRect(20, 90, 171, 22))
        self.desc_line.setObjectName("desc_line")
        self.cost_line = QtWidgets.QLineEdit(Dialog)
        self.cost_line.setGeometry(QtCore.QRect(230, 90, 171, 22))
        self.cost_line.setObjectName("cost_line")
        self.date_line = QtWidgets.QLineEdit(Dialog)
        self.date_line.setGeometry(QtCore.QRect(20, 150, 321, 22))
        self.date_line.setObjectName("date_line")
        self.add_btn = QtWidgets.QPushButton(Dialog)
        self.add_btn.setGeometry(QtCore.QRect(110, 190, 191, 31))
        self.add_btn.setObjectName("add_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Ремонт"))
        self.label.setText(_translate("Dialog", "Номер машины"))
        self.label_2.setText(_translate("Dialog", "ИД мастерской"))
        self.label_3.setText(_translate("Dialog", "Задание"))
        self.label_4.setText(_translate("Dialog", "Стоимость"))
        self.label_5.setText(_translate("Dialog", "Дата начала работы (формат гггг-мм-дд)"))
        self.add_btn.setText(_translate("Dialog", "Отправить на ремонт"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
