# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\EGOR\Desktop\cursach\Course\TechUserWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 771, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 210, 101, 31))
        self.comboBox.setObjectName("comboBox")
        self.email_line = QtWidgets.QLineEdit(self.centralwidget)
        self.email_line.setGeometry(QtCore.QRect(530, 370, 241, 22))
        self.email_line.setObjectName("email_line")
        self.name_lbl = QtWidgets.QLabel(self.centralwidget)
        self.name_lbl.setGeometry(QtCore.QRect(530, 250, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_lbl.setFont(font)
        self.name_lbl.setObjectName("name_lbl")
        self.name_line = QtWidgets.QLineEdit(self.centralwidget)
        self.name_line.setGeometry(QtCore.QRect(530, 270, 241, 22))
        self.name_line.setObjectName("name_line")
        self.phone_lbl = QtWidgets.QLabel(self.centralwidget)
        self.phone_lbl.setGeometry(QtCore.QRect(530, 300, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phone_lbl.setFont(font)
        self.phone_lbl.setObjectName("phone_lbl")
        self.phone_line = QtWidgets.QLineEdit(self.centralwidget)
        self.phone_line.setGeometry(QtCore.QRect(530, 320, 241, 22))
        self.phone_line.setObjectName("phone_line")
        self.email_lbl = QtWidgets.QLabel(self.centralwidget)
        self.email_lbl.setGeometry(QtCore.QRect(530, 350, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.email_lbl.setFont(font)
        self.email_lbl.setObjectName("email_lbl")
        self.update_btn = QtWidgets.QPushButton(self.centralwidget)
        self.update_btn.setGeometry(QtCore.QRect(530, 410, 241, 41))
        self.update_btn.setObjectName("update_btn")
        self.inf_lbl = QtWidgets.QLabel(self.centralwidget)
        self.inf_lbl.setGeometry(QtCore.QRect(530, 210, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.inf_lbl.setFont(font)
        self.inf_lbl.setObjectName("inf_lbl")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Тех. поддержка"))
        self.name_lbl.setText(_translate("MainWindow", "ФИО"))
        self.phone_lbl.setText(_translate("MainWindow", "Телефон"))
        self.email_lbl.setText(_translate("MainWindow", "Email"))
        self.update_btn.setText(_translate("MainWindow", "Обновить информацию"))
        self.inf_lbl.setText(_translate("MainWindow", "Информация о пользователе:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
