# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\EGOR\Desktop\cursach\Course\WorkshopWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(251, 230)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.mail_line = QtWidgets.QLineEdit(Dialog)
        self.mail_line.setGeometry(QtCore.QRect(10, 40, 231, 21))
        self.mail_line.setObjectName("mail_line")
        self.phone_line = QtWidgets.QLineEdit(Dialog)
        self.phone_line.setGeometry(QtCore.QRect(10, 100, 231, 21))
        self.phone_line.setObjectName("phone_line")
        self.fax_line = QtWidgets.QLineEdit(Dialog)
        self.fax_line.setGeometry(QtCore.QRect(10, 160, 231, 21))
        self.fax_line.setObjectName("fax_line")
        self.add_button = QtWidgets.QPushButton(Dialog)
        self.add_button.setGeometry(QtCore.QRect(70, 190, 101, 31))
        self.add_button.setObjectName("add_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Новая автомастерская"))
        self.label.setText(_translate("Dialog", "Электронная почта"))
        self.label_2.setText(_translate("Dialog", "Телефон"))
        self.label_3.setText(_translate("Dialog", "Факс"))
        self.add_button.setText(_translate("Dialog", "Добавить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
